//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptiCipAdministratorHelper2.Areas.MainWindow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptiCipAdministratorHelper2.Areas.MainWindow.Resources.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language will be changed on &quot;{0}&quot; at the next time you start..
        /// </summary>
        public static string ChangeLangMessage {
            get {
                return ResourceManager.GetString("ChangeLangMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings.
        /// </summary>
        public static string ChangeLangMessageBoxName {
            get {
                return ResourceManager.GetString("ChangeLangMessageBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHNEIDER-ELECTRIC ESS RUSSIA.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string NavHelp {
            get {
                return ResourceManager.GetString("NavHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string NavInfo {
            get {
                return ResourceManager.GetString("NavInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string NavLanguage {
            get {
                return ResourceManager.GetString("NavLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiCip.
        /// </summary>
        public static string NavOptiCipConfig {
            get {
                return ResourceManager.GetString("NavOptiCipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NavOptiCipConfigOpen {
            get {
                return ResourceManager.GetString("NavOptiCipConfigOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string NavSelectEnLanguage {
            get {
                return ResourceManager.GetString("NavSelectEnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string NavSelectRuLanguage {
            get {
                return ResourceManager.GetString("NavSelectRuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string NavTools {
            get {
                return ResourceManager.GetString("NavTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opc config creator.
        /// </summary>
        public static string NavToolsOpcCreator {
            get {
                return ResourceManager.GetString("NavToolsOpcCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opticip usergroup.
        /// </summary>
        public static string NavUserGroup {
            get {
                return ResourceManager.GetString("NavUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTICIP administrator helper 2.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somethink wrong, try to add group by computer managment.
        /// </summary>
        public static string UserGroupAddingNotSuccess {
            get {
                return ResourceManager.GetString("UserGroupAddingNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UserGroupAddingSuccess {
            get {
                return ResourceManager.GetString("UserGroupAddingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add groups?.
        /// </summary>
        public static string UserGroupAddUserLabel {
            get {
                return ResourceManager.GetString("UserGroupAddUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all necessary groups are present!.
        /// </summary>
        public static string UserGroupGroupIsNotOk {
            get {
                return ResourceManager.GetString("UserGroupGroupIsNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All necessary groups are present..
        /// </summary>
        public static string UserGroupGroupIsOk {
            get {
                return ResourceManager.GetString("UserGroupGroupIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add users, run the program from the administrator.
        ///For the functioning of the opticip viewer, the system must have the following user groups OPTICIP_ADMINISTRATORS, OPTICIP_MANAGERS, OPTICIP_USERS..
        /// </summary>
        public static string UserGroupInfo {
            get {
                return ResourceManager.GetString("UserGroupInfo", resourceCulture);
            }
        }
    }
}
