//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptiCipAdministratorHelper2.Areas.OptiCipConfig.AddLineTag.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptiCipAdministratorHelper2.Areas.OptiCipConfig.AddLineTag.Resources.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XLSX file.
        /// </summary>
        public static string ButtonSelectFile {
            get {
                return ResourceManager.GetString("ButtonSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get tags.
        /// </summary>
        public static string GetTagsFromFile {
            get {
                return ResourceManager.GetString("GetTagsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter name column name.
        /// </summary>
        public static string LabelFilterNameColumnName {
            get {
                return ResourceManager.GetString("LabelFilterNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value.
        /// </summary>
        public static string LabelFilterValue {
            get {
                return ResourceManager.GetString("LabelFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias column name.
        /// </summary>
        public static string LabelTagAliasColumnName {
            get {
                return ResourceManager.GetString("LabelTagAliasColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color column name.
        /// </summary>
        public static string LabelTagColorColumnName {
            get {
                return ResourceManager.GetString("LabelTagColorColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label column name.
        /// </summary>
        public static string LabelTagLabelColumnName {
            get {
                return ResourceManager.GetString("LabelTagLabelColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name column name .
        /// </summary>
        public static string LabelTagNameColumnName {
            get {
                return ResourceManager.GetString("LabelTagNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag type column name.
        /// </summary>
        public static string LabelTagTypeColumnName {
            get {
                return ResourceManager.GetString("LabelTagTypeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag units column name.
        /// </summary>
        public static string LabelTagUnitsColumnName {
            get {
                return ResourceManager.GetString("LabelTagUnitsColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet number.
        /// </summary>
        public static string LabelWorksheetNumber {
            get {
                return ResourceManager.GetString("LabelWorksheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value.
        /// </summary>
        public static string MaxValueColumnName {
            get {
                return ResourceManager.GetString("MaxValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min value.
        /// </summary>
        public static string MinValueColumnName {
            get {
                return ResourceManager.GetString("MinValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opc short line name.
        /// </summary>
        public static string OpcShortLinkName {
            get {
                return ResourceManager.GetString("OpcShortLinkName", resourceCulture);
            }
        }
    }
}
